version: '3'

services:
  frontend:
    build:
      context: .
      dockerfile: frontend.Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./App:/app

  backend:
    build:
      context: .
      dockerfile: backend.Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./Server:/app

  db:
    build:
      context: .
      dockerfile: database/Dockerfile
    ports:
      - "5432:5432"
    volumes:
      - ./database:/database
