# docker-compose.yml

version: '3.8'

services:
  app:
    build: ./App
    ports:
      - "3000:3000"
    depends_on:
      - server
  server:
    build: ./Server
    ports:
      - "8000:8000"
    depends_on:
      - database
  database:
    build: ./Server/database
    # No need to expose ports for SQLite
