# docker-compose.yml

version: '3'

services:
  backend:
    build:
      context: Server
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./Server:/app

  frontend:
    build:
      context: App
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./App:/app

  database:
    build:
      context: Server/database
      dockerfile: Dockerfile
    volumes:
      - database_data:/database

volumes:
  database_data:
